# Generated by Django 4.1.4 on 2022-12-17 22:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_paymentdetails_category_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Фирма', 'verbose_name_plural': 'Фирмы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'verbose_name': 'Заказ товаров', 'verbose_name_plural': 'Заказы товаров'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name': 'Реквизиты', 'verbose_name_plural': 'Реквизиты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В работе', 'In Progress'), ('Отменён', 'Closed'), ('Завершён', 'Completed')], default='В работе', max_length=10, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название фирмы'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='origin',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна изготовления'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tel',
            field=models.CharField(max_length=14, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='item_pictures/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.batch', verbose_name='Поставка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brand', verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('Новый', 'New'), ('Б/у', 'Used'), ('Уценка', 'Discount')], default='Новый', max_length=10, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='item_pictures/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выполнения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2022, 12, 18), verbose_name='Дата размещения заказа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
    ]
