# Generated by Django 4.1.4 on 2022-12-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_pictures/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_pictures/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGR', 'В работе'), ('CLOSED', 'Отменён'), ('COMPLETED', 'Завершён')], default='IN_PROGR', max_length=10, verbose_name='Состояние'),
        ),
    ]
