# Generated by Django 4.1.4 on 2022-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_image_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Адрес самовывоза',
                'verbose_name_plural': 'Адрес самовывоза',
            },
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
