# Generated by Django 4.1.4 on 2022-12-18 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_client_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Почта'),
        ),
    ]
