# Generated by Django 4.1.4 on 2022-12-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_order_status_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='cost',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order', verbose_name='Заказ'),
        ),
    ]
